repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.10
  -   repo: https://gitlab.com/pycqa/flake8
      rev: '4.0.1'
      hooks:
        -   id: flake8
            additional_dependencies: [
                'flake8-variables-names==0.0.4',
            ]
  -   repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
        -   id: isort
